const Ddata=[
  {
    cover:"../images/i1.jpeg",
    name:"Water Bottle",
    price:800,
  },
  {
    cover:"../images/i2.jpeg",
    name:"Socks",
    price:500,
  },
  {
    cover:"../images/i3.jpg",
    name:"Ties",
    price:400,
  },
  {
    cover:"../images/i4.jpg",
    name:"Slippers",
    price:700,
  },
  {
    cover:"../images/04.jpg",
    name:"Belts",
    price:300,
  },
  {
    cover:"../images/i1.jpeg",
    name:"Underwears",
    price:200,
  },
  {
    cover:"../images/i1.jpeg",
    name:"Gloves",
    price:150,
  },
  {
    cover:"../images/i2.jpeg",
    name:"Jackets",
    price:1500,
  },
  {
    cover:"../images/i3.jpg",
    name:"Tousers",
    price:1500,
  },
]

export default Ddata