const Data={
productItems:[
  {
    id:1,
    discount:50,
    cover:"../images/balency.jpg",
    name:"Shoes",
    price:2500,
  },
  {
    id:2,
    discount:50,
    cover:"../images/jordan.jpg",
    name:"Shoes",
    price:2500,
  },
  {
    id:3,
    discount:50,
    cover:"../images/jordan.jpg",
    name:"Shoes",
    price:2500,
  },
  {
    id:4,
    discount:50,
    cover:"../images/jordan.jpg",
    name:"Shoes",
    price:2500,
  },
  {
    id:5,
    discount:50,
    cover:"../images/balency.jpg",
    name:"Shoes",
    price:2500,
  },
  {
    id:6,
    discount:50,
    cover:"../images/balency.jpg",
    name:"Shoes",
    price:1500,
  },
]

}
export default Data